on:
  pull_request:

concurrency:
  group: pr-${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Mint
        run: npm i -g mint
      - name: Broken Link Check
        run: |
          set -o pipefail
          mint broken-links | tee output.log
          if ! grep -q "success" output.log; then
            echo "No success found in log. Exiting."
            exit 1
          fi
