on:
  pull_request:

name: Broken Link Check
jobs:
  check:
    name: Broken Link Check
    runs-on: ubuntu-latest
    steps:
      - name: Install Mintlify CLI
        run: npm i -g mint
      - name: Broken Link Check
        run: mint broken-links
